#!/usr/bin/env node
// fetch-oui.mjs — download the IEEE MA-L registry and generate web/lib/oui-data.js.
//
// The registry maps the first three bytes of a MAC address to the company that
// registered the block, which is how the dashboard names a router's maker even
// when the AP advertises no WPS element. Committing the generated module means
// Vercel bundles it into the function; no runtime fetch is involved.

import { writeFileSync, mkdirSync } from 'node:fs';
import { normaliseVendorName } from '../web/lib/oui.mjs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = 'https://standards-oui.ieee.org/oui/oui.csv';
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'web', 'lib', 'oui-data.js');
const CSV = join(dirname(fileURLToPath(import.meta.url)), '..', 'server', 'data', 'oui.csv');

console.log(`Downloading ${SRC} …`);

let text;
try {
  const res = await fetch(SRC, {
    headers: { 'User-Agent': 'wifi-scout/1.0 (+oui updater)' },
    signal: AbortSignal.timeout(120000),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
  text = await res.text();
} catch (err) {
  console.error(`\nDownload failed: ${err.message}`);
  console.error('The dashboard still works — it falls back to the built-in vendor table.');
  process.exit(1);
}

console.log(`Received ${(text.length / 1e6).toFixed(1)} MB, parsing…`);

const map = Object.create(null);
for (const line of text.split('\n')) {
  const m = line.match(/^MA-L,([0-9A-Fa-f]{6}),(?:"((?:[^"]|"")*)"|([^,]*))/);
  if (!m) continue;
  let name = (m[2] ? m[2].replace(/""/g, '"') : m[3] || '').trim();
  if (!name) continue;
  name = normaliseVendorName(name);
  if (!name) continue;
  map[m[1].toUpperCase()] = name;
}

const count = Object.keys(map).length;
if (count < 1000) {
  console.error(`Only parsed ${count} entries — the format may have changed. Aborting.`);
  process.exit(1);
}

const body = `// oui-data.js — generated by tools/fetch-oui.mjs. Do not edit by hand.
// Source: IEEE MA-L registry (${SRC})
// Entries: ${count}

export const OUI = ${JSON.stringify(map, null, 0)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);

// The local server can also read the CSV directly, which keeps it current
// without a rebuild.
try {
  mkdirSync(dirname(CSV), { recursive: true });
  writeFileSync(CSV, text);
} catch { /* optional */ }

console.log(`\nWrote ${count} vendor entries to web/lib/oui-data.js`);
console.log('Commit that file so the Vercel deployment picks it up.');
